// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iahjepkbjapxqsdsgiob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhaGplcGtiamFweHFzZHNnaW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc2NzEzMzEsImV4cCI6MjA4MzI0NzMzMX0.UCM9afodWNXIltz9sXMj5B1YO-dyPZ2w_cXRhPdrMNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
